### ISSUE TITLE
Installation error after upgrading to R 4.0 (macOS)

### ISSUE THREAD

**Issue by milanmlft** [r-lib/rlang#972]
Hi,

I'm having trouble getting `rlang` installed from source after I upgraded to R 4.0.

The relevant error message after running `install.packages("rlang")` is

```
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I./lib/  -I/usr/local/include   -fPIC  -Wall -g -O2  -c capture.c -o capture.o
In file included from capture.c:1:
/Library/Frameworks/R.framework/Resources/include/Rinternals.h:39:11: fatal error: 'stdio.h' file
      not found
# include <stdio.h>
          ^~~~~~~~~
1 error generated.
make: *** [capture.o] Error 1
ERROR: compilation failed for package ‘rlang’
```

I didn't encounter this when installing under previous versions of R. Any idea what might be causing this?

Thank you very much!

**Comment by lionel-** [comment]
Make sure you've installed the Xcode SDK and accepted the licence via `xcode-select --install`. In your case I don't expect this is the problem.

If you're on Mojave this may help: https://silvae86.github.io/2018/07/05/fixing-missing-headers-for-homebrew-in-mac-osx-mojave. But you're probably on a newer version.

You might want to add this to your `.R/Makevars`:

```
CPPFLAGS += -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include
```

This is a useful guide and it looks like it was just updated: https://thecoatlessprofessor.com/programming/cpp/r-compiler-tools-for-rcpp-on-macos/

It recommends deleting the `.R/Makevars` file, so maybe there's a `CPPFLAGS =` (instead of `+=`) that overwrites the defaults which would work?

**Comment by milanmlft** [comment]
Thanks a lot! 

I didn't have a `.R/Makevars` file so I created one and added 

```
CPPFLAGS += -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include
```

This seems to have done the trick. Hopefully this will stay fixed now.

**Comment by niteshsinghal88** [comment]
I am getting this error..
`trying URL 'https://ftp.belnet.be/mirror/CRAN/src/contrib/rlang_0.4.11.tar.gz'
Content type 'application/octet-stream' length 861727 bytes (841 KB)
==================================================
downloaded 841 KB

* installing *source* package ‘rlang’ ...
** package ‘rlang’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
/usr/bin/gcc -I"/usr/local/R/lib64/R/include" -DNDEBUG -I./lib/  -I/usr/local/include -fvisibility=hidden -fpic  -g -O2  -c capture.c -o capture.o
/usr/bin/gcc -I"/usr/local/R/lib64/R/include" -DNDEBUG -I./lib/  -I/usr/local/include -fvisibility=hidden -fpic  -g -O2  -c export.c -o export.o
In file included from export.c:1:0:
export/exported.c: In function ‘rlang_env_bind_list’:
export/exported.c:93:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for (r_ssize i = 0; i < n; ++i) {
   ^
export/exported.c:93:3: note: use option -std=c99 or -std=gnu99 to compile your code
In file included from export.c:1:0:
export/exported.c: In function ‘rlang_is_string’:
export/exported.c:572:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for (r_ssize i = 0; i < n; ++i) {
   ^
make: *** [export.o] Error 1
ERROR: compilation failed for package ‘rlang’
* removing ‘/root/R/x86_64-pc-linux-gnu-library/3.6/rlang’

The downloaded source packages are in
        ‘/tmp/RtmpBazQmG/downloaded_packages’
Warning message:
In install.packages("rlang") :
  installation of package ‘rlang’ had non-zero exit status
`

**Comment by niteshsinghal88** [comment]
Can you please suggest on my error also.. I already tried the above solution but that's not working for me..

``trying URL https://ftp.belnet.be/mirror/CRAN/src/contrib/rlang_0.4.11.tar.gz``
``Content type application/octet-stream length 861727 bytes (841 KB)``
``
``downloaded 841 KB``
``
``installing source package ‘rlang’ ...``
`package ‘rlang’ successfully unpacked and MD5 sums checked`
`using staged installation`
`libs`
`/usr/bin/gcc -I"/usr/local/R/lib64/R/include" -DNDEBUG -I./lib/  -I/usr/local/include -fvisibility=hidden -fpic  -g -O2  -c capture.c -o capture.o`
`/usr/bin/gcc -I"/usr/local/R/lib64/R/include" -DNDEBUG -I./lib/  -I/usr/local/include -fvisibility=hidden -fpic  -g -O2  -c export.c -o export.o`
`In file included from export.c:1:0:`
`export/exported.c: In function ‘rlang_env_bind_list’:`
`export/exported.c:93:3: error: ‘for’ loop initial declarations are only allowed in C99 mode`
`   for (r_ssize i = 0; i < n; ++i) {`
`   ^`
`export/exported.c:93:3: note: use option -std=c99 or -std=gnu99 to compile your code`
`In file included from export.c:1:0:`
`export/exported.c: In function ‘rlang_is_string’:`
`export/exported.c:572:3: error: ‘for’ loop initial declarations are only allowed in C99 mode`
`   for (r_ssize i = 0; i < n; ++i) {`
`   ^`
`make: *** [export.o] Error 1`
`ERROR: compilation failed for package ‘rlang’`
`* removing ‘/root/R/x86_64-pc-linux-gnu-library/3.6/rlang’`
``
`The downloaded source packages are in`
`        ‘/tmp/RtmpBazQmG/downloaded_packages’`
`Warning message:`
`In install.packages("rlang") :`
`  installation of package ‘rlang’ had non-zero exit status``

**Comment by lionel-** [comment]
Maybe add `CFLAGS = -std=c99` to your `.R/Makevars` file? No idea why you need that though. What version of gcc do you have?

**Comment by niteshsinghal88** [comment]
Hi @lionel-  thanks for your response. I tried your suggestion but still no luck.

here are my current settings.

``]# cat /root/.R/Makevars`
``
`CXX14FLAGS=-O3 -march=native -mtune=native -fPIC`
`CXX14=/opt/rh/devtoolset-8/root/usr/bin/g++`
``
`CXX14FLAGS=-O3 -march=native -mtune=native -fPIC`
`CXX14=/opt/rh/devtoolset-8/root/usr/bin/g++`
``
`CXX14FLAGS=-O3 -march=native -mtune=native -fPIC`
`CXX14=/opt/rh/devtoolset-8/root/usr/bin/g++`
``
`CXX14FLAGS=-O3 -march=native -mtune=native -fPIC`
`CXX14=/opt/rh/devtoolset-8/root/usr/bin/g++`
``
`#CXX11 = g++`
`CXX11FLAGS = -O2 -g $(LTO)`
`CXX11PICFLAGS = -fPIC`
`CXX11STD = -std=c++11`
``
`CC=/usr/bin/gcc`
`CXX=/usr/bin/g++`
`CXX11=/usr/bin/g++`
`CPPFLAGS += -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include`
`CFLAGS = -std=c99`
```
``
`]# rpm -qa | grep gcc`
`gcc-4.8.5-44.el7.x86_64`
`gcc-c++-4.8.5-44.el7.x86_64`
`libgcc-4.8.5-44.el7.x86_64`
`gcc-gfortran-4.8.5-44.el7.x86_64`
`libgcc-4.8.5-44.el7.i686`
``
``> packageurl <- "https://cran.r-project.org/src/contrib/rlang_0.4.11.tar.gz"`
``
`install.packages(packageurl, repos=NULL, type="source", lib="/usr/lib64/R/library")`
`trying URL 'https://cran.r-project.org/src/contrib/rlang_0.4.11.tar.gz'`
`Content type 'application/x-gzip' length 861727 bytes (841 KB)`
``
`downloaded 841 KB`
``
`installing source package ‘rlang’ ...`
`** package ‘rlang’ successfully unpacked and MD5 sums checked`
`** using staged installation`
`** libs`
`/usr/bin/gcc -I"/usr/local/R/lib64/R/include" -DNDEBUG -I./lib/ -I/usr/local/include -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include -fvisibility=hidden -fpic -std=c99 -c capture.c -o capture.o`
`In file included from capture.c:1:0:`
`/usr/local/R/lib64/R/include/Rinternals.h:39:20: fatal error: stdio.h: No such file or directory`
`include <stdio.h>`
`^`
`compilation terminated.`
`make: *** [capture.o] Error 1`
`ERROR: compilation failed for package ‘rlang’`
`removing ‘/usr/lib64/R/library/rlang’`
`restoring previous ‘/usr/lib64/R/library/rlang’`
`Warning message:`
`In install.packages(packageurl, repos = NULL, type = "source", lib = "/usr/lib64/R/library") :`
`installation of package ‘/tmp/RtmpLOjmaJ/downloaded_packages/rlang_0.4.11.tar.gz’ had non-zero exit status`
```

**Comment by lionel-** [comment]
It's strange that you include the macOS SDK in your CPPFLAGS when you are on Linux.

It looks like it doesn't find `stdio.h` which is in the standard C lib, so try finding out the correct path on your computer and add it to `-I` in `CPPFLAGS.

**Comment by niteshsinghal88** [comment]
Hi @lionel-  thanks a million..!
I corrected the path for `stdio.h` and that fixed my issues. 

For the macOS SDK in my CPPFLAGS --  I actually copied it from this thread only and didn't realize that it's for MacOS. https://github.com/r-lib/rlang/issues/972#issuecomment-624542621

Can you please advise what should I put there for RHEL 7.9?

**Comment by lionel-** [comment]
I don't know because this sort of stuff is platform dependent. Normally, if your R is correctly configured by the packager of your distribution, you shouldn't have to specify fundamental include paths like this (I think).
